version: '3.8'
services:
  mongodb:
    container_name: gmongodb
    image: 'mongo'
    volumes:
      - data:/data/db
  backend:
    container_name: gbackend
    build: ./backend
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongodb
    ports:
      - '3300:80'
  frontend:
    container_name: gfrontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
    ports:
      - '3301:3000'

volumes:
  data:
  logs:
